[tox]
envlist = py310
skipsdist = True

[testenv]
basepython = python3.10
deps =
    robotframework
    robotframework-browser
    robotframework-retryfailed
    requests
    
commands =
    rfbrowser clean-node
    python -m Browser.entry init
    xvfb-run -a python -m robot --outputdir results TestCases
